# Generated by Django 5.2.4 on 2025-08-03 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('amount_paid', models.PositiveIntegerField(default=0)),
                ('registration_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.registration')),
            ],
        ),
    ]
