# Generated by Django 4.2 on 2025-08-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventposter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventposter',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posters', to='events.event'),
        ),
    ]
