# Generated by Django 4.2 on 2025-08-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventposter_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventposter',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
